//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kibicom.wd_1c_trans_gdi {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class set : global::System.Configuration.ApplicationSettingsBase {
        
        private static set defaultInstance = ((set)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new set())));
        
        public static set Default {
            get {
                return defaultInstance;
            }
        }
    }
}
